transition_markers = {
  "leading_markers": {
    "topic_continuity": {
      "and",
      "so",
      "nor",
      "also",
      "furthermore",
      "moreover",
      "in addition",
      "as well",
      "besides",
      "additionally",
      "not to mention",
      "plus",
      "what is more",
      "all in all",
      "for one thing",
      "in the same vein",
      "on top of that",
      "namely",
      "to put it differently",
      "to add to that",
      "all things considered",
      "in detail",
      "specifically",
      "as a matter of fact",
      "in particular",
      "to elaborate",
      "to expand on that",
      "to illustrate this point",
      "to phrase it another way",
      "to reiterate",
      "for further clarification",
      "expounding upon this",
      "to delve deeper",
      "further expounding",
      "for instance",
      "for example",
      "as evidenced by",
      "to illustrate",
      "such as",
      "consider the case of",
      "take, for example",
      "illustrated by",
      "demonstrated by",
      "first,",
      "first of all",
      "secondly",
      "thirdly",
      "thereafter",
      "subsequently",
      "finally",
      "at first",
      "later",
      "next,",
      "afterwards",
      "in conclusion",
      "to sum up",
      "to conclude",
      "in summary",
      "as soon as",
      "after all",
      "following this",
      "preceding this",
      "thereupon",
      "henceforth",
      "in the next step",
      "in the final analysis",
      "for this purpose",
      "for this reason",
      "to that end",
      "to this end",
      "in order to",
      "in order that",
      "so that",
      "with this in mind",
      "with this intention",
      "considering that",
      "given that",
      "because",
      "due to",
      "as a result of",
      "resulting from",
      "resulting in",
      "therefore",
      "thus",
      "hence",
      "for the sake of",
      "with the aim of",
      "with the goal of",
      "with the purpose of",
      "to achieve",
      "to fulfill",
      "in pursuit of",
      "aimed at",
      "geared towards",
      "as a means to",
      "indeed",
      "actually",
      "certainly",
      "of course",
      "in fact",
      "truly",
      "undoubtedly",
      "without a doubt",
      "clearly",
      "obviously",
      "evidently",
      "in reality",
      "in truth",
      "naturally",
      "notably",
      "unquestionably",
      "assuredly",
      "most importantly",
      "without question",
      "beyond doubt",
      "inarguably",
      "decidedly",
      "emphatically",
      "unequivocally",
      "categorically",
      "irrefutably",
      "explicitly",
      "conclusively",
      "to rephrase",
      "to put it another way",
      "that is to say",
      "simply put",
      "in simpler terms",
      "in essence",
      "essentially",
      "more precisely",
      "to explain further",
      "putting it differently",
      "this means that",
      "in a different light",
      "put another way",
      "to simplify",
      "to paraphrase"
      "in other terms",
      "stated differently",
      "to express it differently",
      "in other parlance",
      "rewording",
      "alternatively stated",
      "for further clarification",
      "to restate",
      "summing up",
      "recasting it as",
      "number one"
    },
    "topic_shift": {
      "but",
      "or",
      "however",
      "on the contrary",
      "on the other hand",
      "nevertheless",
      "nonetheless",
      "in contrast",
      "conversely",
      "although",
      "though",
      "despite",
      "instead",
      "whereas",
      "while",
      "in comparison",
      "by contrast",
      "yet",
      "as opposed to",
      "contrarily",
      "differently",
      "unlike",
      "in opposition to",
      "contradictorily",
      "as a counterpoint",
      "on a different note",
      "contrasting with",
      "opposed to",
      "in defiance of",
      "in spite of",
      "even though",
      "still",
      "admittedly",
      "granted that",
      "even if",
      "assuming that",
      "even so",
      "regardless",
      "notwithstanding",
      "on one hand",
      "be that as it may",
      "all the same",
      "notwithstanding the fact that",
      "albeit",
      "with this in mind",
      "bearing this in mind",
      "even bearing in mind",
      "taking into account",
      "contrary to",
      "rather",
      "to the contrary",
      "that being said",
      "to clarify",
      "upon further examination",
      "reexamining this",
      "on closer inspection",
      "surprisingly",
      "contradictorily",
      "reconsidering this",
      "revision suggests",
      "counter to this",
      "against this backdrop",
      "later",
      "following this",
      "previously",
      "initially",
      "lastly",
      "eventually",
      "until",
      "meanwhile",
      "in the meantime",
      "as soon as",
      "thereafter",
      "consequently",
      "at first",
      "in the early stages",
      "following that",
      "at a later stage",
      "in the final analysis",
      "in the end",
      "prior to this",
      "after a while",
      "in the following phase"
      "elsewhere",
      "nearby",
      "opposite",
      "adjacent",
      "beyond",
      "alongside",
      "amid",
      "among",
      "between",
      "across",
      "around",
      "behind",
      "beneath",
      "beside",
      "in front of",
      "within",
      "to the left",
      "to the right",
      "in the center",
      "at the top",
      "at the bottom",
      "surrounding",
      "over",
      "throughout",
      "across from",
      "in the vicinity of"
    },
  },
  "flexible_markers": {
    "topic_continuity": {
      "as well",
      "in tandem with",
      "coupled with",
      "but also",
      "together with",
      "in conjunction with",
      "side by side with",
      "simultaneously with",
      "on top of",
      "this includes",
      "this entails",
      "this involves",
      "in other words",
      "which means",
      "signifying",
      "this suggests",
      "this indicates",
      "to put it another way",
      "to clarify",
      "to elaborate",
      "in essence",
      "put differently",
      "for instance",
      "for example",
      "such as",
      "including" 
      "particularly",
      "to illustrate",
      "demonstrated by",
      "evidenced by",
      "exemplified by",
      "take the case of",
      "as an example",
      "in particular",
      "thereafter",
      "following this",
      "subsequent to",
      "consequently",
      "preceding this",
      "meanwhile",
      "simultaneously",
      "thereupon",
      "after that",
      "in the meantime",
    },
    "topic_shift": {
      ""
    }
  }
}

oppose_adj = {
  "oppose",
  "against",
  "wrong",
  "bad",
  "harmful",
  "clear",
  "mistake",
  "mistaken",
  "profound",
  "dangerous",
  "broad",
  "greater",
  "major",
  "unrelenting",
  "small",
  "terrible",
  "dangerous",
  }
