transition_markers = {
  "leading_markers": {
    "topic_continuity": {
      "and",
      "so",
      "nor",
      "also",
      "furthermore",
      "moreover",
      "in addition",
      "as well",
      "besides",
      "additionally",
      "not to mention",
      "plus",
      "what is more",
      "all in all",
      "for one thing",
      "in the same vein",
      "on top of that",
      "namely",
      "to put it differently",
      "to add to that",
      "all things considered",
      "in detail",
      "specifically",
      "as a matter of fact",
      "in particular",
      "to elaborate",
      "to expand on that",
      "to illustrate this point",
      "to phrase it another way",
      "to reiterate",
      "for further clarification",
      "expounding upon this",
      "to delve deeper",
      "further expounding",
      "for instance",
      "for example",
      "as evidenced by",
      "to illustrate",
      "such as",
      "consider the case of",
      "take, for example",
      "illustrated by",
      "demonstrated by",
      "first,",
      "first of all",
      "secondly",
      "thirdly",
      "thereafter",
      "subsequently",
      "finally",
      "at first",
      "later",
      "next,",
      "afterwards",
      "in conclusion",
      "to sum up",
      "to conclude",
      "in summary",
      "as soon as",
      "after all",
      "following this",
      "preceding this",
      "thereupon",
      "henceforth",
      "in the next step",
      "in the final analysis",
      "for this purpose",
      "for this reason",
      "to that end",
      "to this end",
      "in order to",
      "in order that",
      "so that",
      "with this in mind",
      "with this intention",
      "considering that",
      "given that",
      "because",
      "due to",
      "as a result of",
      "resulting from",
      "resulting in",
      "therefore",
      "thus",
      "hence",
      "for the sake of",
      "with the aim of",
      "with the goal of",
      "with the purpose of",
      "to achieve",
      "to fulfill",
      "in pursuit of",
      "aimed at",
      "geared towards",
      "as a means to",
      "indeed",
      "actually",
      "certainly",
      "of course",
      "in fact",
      "truly",
      "undoubtedly",
      "without a doubt",
      "clearly",
      "obviously",
      "evidently",
      "in reality",
      "in truth",
      "naturally",
      "notably",
      "unquestionably",
      "assuredly",
      "most importantly",
      "without question",
      "beyond doubt",
      "inarguably",
      "decidedly",
      "emphatically",
      "unequivocally",
      "categorically",
      "irrefutably",
      "explicitly",
      "conclusively",
      "to rephrase",
      "to put it another way",
      "that is to say",
      "simply put",
      "in simpler terms",
      "in essence",
      "essentially",
      "more precisely",
      "to explain further",
      "putting it differently",
      "this means that",
      "in a different light",
      "put another way",
      "to simplify",
      "to paraphrase"
      "in other terms",
      "stated differently",
      "to express it differently",
      "in other parlance",
      "rewording",
      "alternatively stated",
      "for further clarification",
      "to restate",
      "summing up",
      "recasting it as",
      "number one"
    },
    "topic_shift": {
      "but",
      "or",
      "however",
      "on the contrary",
      "on the other hand",
      "nevertheless",
      "nonetheless",
      "in contrast",
      "conversely",
      "although",
      "though",
      "despite",
      "instead",
      "whereas",
      "while",
      "in comparison",
      "by contrast",
      "yet",
      "as opposed to",
      "contrarily",
      "differently",
      "unlike",
      "in opposition to",
      "contradictorily",
      "as a counterpoint",
      "on a different note",
      "contrasting with",
      "opposed to",
      "in defiance of",
      "in spite of",
      "even though",
      "still",
      "admittedly",
      "granted that",
      "even if",
      "assuming that",
      "even so",
      "regardless",
      "notwithstanding",
      "on one hand",
      "be that as it may",
      "all the same",
      "notwithstanding the fact that",
      "albeit",
      "with this in mind",
      "bearing this in mind",
      "even bearing in mind",
      "taking into account",
      "contrary to",
      "rather",
      "to the contrary",
      "that being said",
      "to clarify",
      "upon further examination",
      "reexamining this",
      "on closer inspection",
      "surprisingly",
      "contradictorily",
      "reconsidering this",
      "revision suggests",
      "counter to this",
      "against this backdrop",
      "later",
      "following this",
      "previously",
      "initially",
      "lastly",
      "eventually",
      "until",
      "meanwhile",
      "in the meantime",
      "as soon as",
      "thereafter",
      "consequently",
      "at first",
      "in the early stages",
      "following that",
      "at a later stage",
      "in the final analysis",
      "in the end",
      "prior to this",
      "after a while",
      "in the following phase"
      "elsewhere",
      "nearby",
      "opposite",
      "adjacent",
      "beyond",
      "alongside",
      "amid",
      "among",
      "between",
      "across",
      "around",
      "behind",
      "beneath",
      "beside",
      "in front of",
      "within",
      "to the left",
      "to the right",
      "in the center",
      "at the top",
      "at the bottom",
      "surrounding",
      "over",
      "throughout",
      "across from",
      "in the vicinity of"
    },
  },
  "flexible_markers": {
    "topic_continuity": {
      "as well",
      "in tandem with",
      "coupled with",
      "but also",
      "together with",
      "in conjunction with",
      "side by side with",
      "simultaneously with",
      "on top of",
      "this includes",
      "this entails",
      "this involves",
      "in other words",
      "which means",
      "signifying",
      "this suggests",
      "this indicates",
      "to put it another way",
      "to clarify",
      "to elaborate",
      "in essence",
      "put differently",
      "for instance",
      "for example",
      "such as",
      "including"
      "particularly",
      "to illustrate",
      "demonstrated by",
      "evidenced by",
      "exemplified by",
      "take the case of",
      "as an example",
      "in particular",
      "thereafter",
      "following this",
      "subsequent to",
      "consequently",
      "preceding this",
      "meanwhile",
      "simultaneously",
      "thereupon",
      "after that",
      "in the meantime",
    },
    "topic_shift": {
      ""
    }
  }
}

oppose_adj = {
  "oppose",
  "against",
  "wrong",
  "bad",
  "harmful",
  "clear",
  "mistake",
  "mistaken",
  "profound",
  "dangerous",
  "broad",
  "greater",
  "major",
  "unrelenting",
  "small",
  "terrible",
  "dangerous",
}

neutral_verbs = [
  "run", "observe", "manage", "organize", "develop", "maintain", "compare", "describe",
  "report", "examine", "determine", "record", "address", "identify", "access", "create",
  "follow", "measure", "discuss", "review", "conduct", "analyze", "present", "apply",
  "utilize", "suggest", "consider", "calculate", "synthesize",
  "quantify", "evaluate", "interpret", "formulate", "validate", "investigate", "correlate", "optimize",
  "integrate", "specify", "simulate", "modify", "fabricate", "illustrate", "derive", "adapt", "enumerate",
  "diagnose", "explore", "implement", "innovate", "elucidate", "catalog", "classify", "deconstruct",
  "replicate", "benchmark", "standardize", "characterize"
]

neutral_verbs = list(set(neutral_verbs))

neutral_adverbs = [
  "objectively", "clearly", "publicly", "officially", "directly", "generally", "globally",
  "nationally", "locally", "effectively", "efficiently", "equally", "precisely", "simply",
  "specifically", "historically", "legally", "politically", "practically", "formally",
  "objectively", "clearly", "publicly", "officially", "directly", "generally", "globally",
  "nationally", "locally", "effectively", "efficiently", "equally", "precisely", "simply",
  "specifically", "historically", "legally", "politically", "practically", "formally",
  "methodically", "analytically", "systematically", "empirically", "theoretically",
  "technically", "experimentally", "quantitatively", "qualitatively", "innovatively",
  "strategically", "academically", "conceptually", "environmentally", "sustainably",
  "ethically", "culturally", "intuitively", "diagnostically", "holistically",
  "statistically", "comprehensively", "dynamically", "virtually", "procedurally"
]

neutral_adverbs = list(set(neutral_adverbs))

neutral_nouns = [
  'candy', 'road', 'table', 'window', 'book', 'chair', 'tree', 'water', 'light', 'phone', 'paper', 'car',
  'glass', 'music', 'art', 'food', 'house', 'garden', 'computer', 'river', 'mountain', 'city', 'village',
  'cloud', 'rain', 'snow', 'sand', 'forest', 'beach', 'bridge', 'candy', 'road', 'table', 'window', 'book',
  'chair', 'tree', 'water', 'light', 'phone', 'paper', 'car',
  'glass', 'music', 'art', 'food', 'house', 'garden', 'computer', 'river', 'mountain', 'city', 'village',
  'cloud', 'rain', 'snow', 'sand', 'forest', 'beach', 'bridge',
  'lake', 'island', 'field', 'moon', 'star', 'planet', 'ocean', 'flower', 'rock', 'hill', 'valley', 'tree',
  'grass', 'leaf', 'bird', 'fish', 'animal', 'sky', 'sun', 'tea', 'coffee', 'cake', 'bicycle', 'train',
  'airplane', 'ship', 'pen', 'pencil', 'notebook', 'basket', 'fence', 'path', 'stream', 'cave', 'cliff', 'desert'
]

neutral_nouns = list(set(neutral_nouns))

bias_words = [
  'family', 'well', 'go', 'year', 'look', 'like', 'life', 'time', 'good', 'america', 'ask', 'come',
  'government', 'man', 'state', 'states', 'want', 'president', 'problem', 'american', 'kind', 'tell',
  'think', 'try', 'world', 'today', 'country', 'child', 'fact', 'people', 'day', 'believe', 'need', 'thing',
  'united', 'great', 'say', 'important', 'nation', 'help', 'deal', 'get', 'lot', 'new', 'right', 'school',
  'entity', 'mean', 'know', 'million', 'thank', 'take', 'issue', 'americans', 'way', 'congress', 'sure',
  'let', 'talk', 'question', 'work', 'happen', 'job'
]

nominalization_suffixes = ('tion', 'ment', 'ness', 'ity', 'age',
                           'ance', 'ence', 'hood', 'ship', 'ty',
                           'cy', 'al', 'ure', 'er', 'ing',
                           'sion', 'ation', 'ibility', 'ana', 'acy',
                           'ama', 'ant', 'dom', 'edge', 'ee',
                           'eer', 'ery', 'ese', 'ess', 'ette',
                           'fest', 'ful', 'iac', 'ian', 'ie',
                           'ion', 'ism', 'ist', 'ite', 'itude',
                           'ium', 'let', 'ling', 'man', 'woman',
                           'mania', 'or', 'th', 'tude', 'ary',
                           'ency', 'ity', 'ship')

discourse_markers = [
  'accordingly', 'actually', 'after', 'after all', 'afterward', 'afterwards', 'all in all', 'also', 'although',
  'always', 'anyway', 'apparently', 'as', 'as a matter of fact', 'as a result', 'as if', 'as long as', 'as soon as',
  'as though', 'as well as', 'assuming that', 'at first', 'at last', 'at least', 'at present', 'at the same time',
  'basically', 'because', 'before', 'being that', 'besides', 'but', 'by the time', 'by the way', 'chiefly', 'clearly',
  'commonly', 'consequently', 'considering that', 'despite', 'due to', 'during', 'either', 'especially',
  'essentially', 'even if', 'even so', 'even supposing', 'even though', 'eventually', 'every', 'evidently', 'except',
  'except for', 'except that', 'exclusively', 'exclusively', 'finally', 'first', 'first of all', 'for example',
  'for instance', 'for one thing', 'for the most part', 'for the time being', 'for this purpose', 'for this reason',
  'formerly', 'forthwith', 'fortunately', 'frankly', 'frequently', 'further', 'furthermore', 'generally',
  'given that', 'granting that', 'hence', 'henceforth', 'honestly', 'however', 'if only', 'immediately',
  'in addition', 'in any case', 'in brief', 'in case', 'in conclusion', 'in contrast', 'in fact', 'in general',
  'in my opinion', 'in order that', 'in order to', 'in other words', 'in particular', 'in short', 'in spite of',
  'in sum', 'in summary', 'in that case', 'in the beginning', 'in the end', 'in the first place', 'in the meantime',
  'in the meanwhile', 'in the same way', 'in the second place', 'in the third place', 'in this case', 'in truth',
  'in view of', 'incidentally', 'including', 'indeed', 'individually', 'initially', 'instantly', 'instead',
  'interestingly', 'just', 'largely', 'last', 'lastly', 'lately', 'later', 'lest', 'like', 'likewise', 'mainly',
  'markedly', 'meanwhile', 'merely', 'moreover', 'most', 'most importantly', 'mostly', 'much namely', 'naturally',
  'neither', 'never', 'nevertheless', 'next', 'nonetheless', 'nor', 'normally', 'not only', 'not just',
  'not to mention',
  'notably', 'notwithstanding', 'now', 'now that', 'nowadays', 'obviously', 'occasionally', 'of course', 'often',
  'on balance', 'on condition that', 'on the contrary', 'on the other hand', 'on the whole', 'once', 'only',
  'ordinarily', 'originally', 'otherwise', 'overall', 'particularly', 'permanently', 'personally', 'plainly', 'plus',
  'presently', 'presently', 'presumably', 'previously', 'primarily', 'privately', 'probably', 'promptly', 'properly',
  'provided that', 'publicly', 'quickly', 'rarely', 'rather', 'readily', 'really', 'recently', 'regardless',
  'regularly', 'relatively', 'remarkably', 'respectively', 'secondly', 'seeing that', 'seemingly', 'seldom',
  'separately', 'seriously', 'seriously', 'shortly', 'shortly', 'significantly', 'similarly', 'similarly', 'simply',
  'since', 'slightly', 'slowly', 'so', 'so far', 'so long as', 'so that', 'sometimes', 'soon', 'specifically',
  'still', 'straightaway', 'strangely', 'strongly', 'subsequently', 'successfully', 'such as', 'suddenly',
  'supposedly', 'supposing', 'surely', 'surprisingly', 'technically', 'temporarily', 'that is way', 'then',
  'thereafter', 'thereby', 'therefore', 'thereupon', 'these days', 'thirdly', 'though', 'thus', 'till',
  'to begin with', 'to conclude', 'to date', 'to illustrate', 'to sum up', 'to tell the truth', 'to that end',
  'to this end', 'to this end', 'typically', 'ultimately', 'undoubtedly', 'unfortunately', 'unless', 'unlike',
  'until', 'until now', 'up to', 'up to now', 'up to the present time', 'usually', 'utterly', 'virtually', 'well',
  'what is more', 'whatever', 'when', 'whenever', 'whereas', 'whereby', 'whereupon', 'wherever', 'whether',
  'whichever', 'while', 'whilst', 'whoever', 'with this in mind', 'with this intention', 'yet'
]

personal_pronouns = ['i', 'me', 'my', 'mine', 'you', 'your', 'yours', 'he', 'him', 'his', 'she', 'her', 'hers', 'it',
                     'its', 'we', 'us', 'our', 'ours', 'they', 'them', 'their', 'theirs']

interjections = [
  'thanks',
  'no',
  '-',
  'goodbye',
  'net',
  'yep',
  'all',
  'god',
  'alright',
  'see',
  'hello',
  'yes',
  'ehh',
  'oh',
  'er',
  'man',
  'hi',
  'darn',
  'hey',
  'gross',
  'anyway',
  'hooray',
  'ok',
  'boom',
  'whoop',
  'gee',
  'nope',
  '--no',
  'please',
  'congratulations',
  'amen',
  'oh--',
  'aye',
  'now',
  'naw',
  'right',
  'thank',
  'augh',
  'um',
  'uh',
  'andy',
  'like',
  'nay',
  'sure',
  'gracious',
  'shit',
  'okay',
  'gosh',
  'huh',
  'oops',
  '-yes',
  'well',
  'bye',
  'boy',
  'say',
  'holy',
  'wow',
  'goodness',
  'fine',
  'unquote',
  'hatch',
  'o',
  'whoa',
  'yea',
  'my',
  'nah',
  '--now',
  'foul',
  'sorry',
  'goodby',
  'welcome',
  'kid',
  'yeah',
  'heavens',
  'ah',
  'whoops',
  'quote',
  'heck'
]

"""------------------------------------------------------------------"""

positive_affect_adj = [
  "amaze",
  "amazing",
  "amused",
  "amusing",
  "appropriate",
  "astonished",
  "astonishing",
  "compel",
  "content",
  "convenient",
  "credible",
  "curious",
  "delighted",
  "delightful",
  "eager",
  "enchanted",
  "fascinate",
  "fascinating",
  "fitting",
  "fortunate",
  "funny",
  "glad",
  "great",
  "happy",
  "hopeful",
  "incredible",
  "indispensable",
  "inevitable",
  "interested",
  "interesting",
  "ironic",
  "jubilant",
  "keen",
  "lucky",
  "merciful",
  "natural",
  "nice",
  "noteworthy",
  "outstanding",
  "overjoyed",
  "please",
  "powerful",
  "predictable",
  "preferable",
  "proper",
  "proof",
  "proud",
  "refresh",
  "relieve",
  "remarkable",
  "satisfy",
  "self-evident",
  "significant",
  "surprise",
  "surprising",
  "thankful",
  "understandable",
  "unexpected"
]

certainty_adj = {
  'unmistakable',
  'indisputable',
  'feasible',
  'certain',
  'determined',
  'express',
  'explicit',
  'unambiguous',
  'inevitable',
  'obvious',
  'unavoidable',
  'undeniable',
  'foolproof',
  'irrefutable',
  'definite',
  'absolute',
  'unqualified',
  'unerring',
  'unwavering',
  'distinct',
  'unimpeachable',
  'flawless',
  'unassailable',
  'clear-cut',
  'evident',
  'assured',
  'manifest',
  'guaranteed',
  'categorical',
  'unconditional',
  'adamant',
  'decisive',
  'unquestionable',
  'inexorable',
  'irrevocable',
  'patent',
  'impeccable',
  'apparent',
  'unfailing',
  'predestined',
  'true',
  'irresistible',
  'possible',
  'infallible',
  'resolute',
  'unyielding',
  'impossible',
  'indubitable',
  'incontrovertible',
  'surefire'
}

certainty_adv = {
  'without doubt',
  'certainly',
  'irrefutably',
  'unmistakably',
  'doubtlessly',
  'without a doubt',
  'beyond question',
  'unquestionably',
  'surely',
  'manifestly',
  'unfailingly',
  'veritably',
  'definitely',
  'conclusively',
  'truly',
  'indeed',
  'explicitly',
  'sure',
  'incontrovertibly',
  'beyond dispute',
  'emphatically',
  'assuredly',
  'indubitably',
  'authoritatively',
  'unambiguously',
  'plainly',
  'decidedly',
  'firmly',
  'incontestably',
  'clearly',
  'actually',
  'unequivocally',
  'indisputably',
  'categorically',
  'undeniably',
  'undoubtedly',
  'without question',
  'absolutely',
  'evidently',
  'irrevocably',
  'unarguably',
  'unerringly',
  'patently',
  'positively',
  'obviously',
  'without fail',
  'beyond a shadow of a doubt',
  'infallibly',
  'beyond doubt',
  'genuinely',
  'for certain'
}

certainty_verbs = {
  'advocate',
  'verify',
  'prove',
  'declare',
  'recognize',
  'ensure',
  'reassure'
  'reassert',
  'ratify',
  'reaffirm',
  'testify',
  'vindicate',
  'determine',
  'confirm',
  'argue',
  'claim',
  'substantiate',
  'understand',
  'show',
  'state',
  'insist',
  'manifest',
  'conclude',
  'uphold',
  'establish',
  'know',
  'avow',
  'ascertain',
  'attest',
  'certify',
  'allege',
  'indicate',
  'guarantee',
  'affirm',
  'defend',
  'maintain',
  'evidence',
  'authenticate',
  'witness',
  'depict',
  'express',
  'corroborate',
  'validate',
  'demonstrate',
  'justify',
  'support',
  'believe',
  'think',
}

doubt_adj = {
  'quizzical',
  'jaded',
  'faltering',
  'wondering',
  'apprehensive',
  'noncommittal',
  'dubious',
  'unsure',
  'vacillating',
  'cynical',
  'guarded',
  'wavering',
  'vacillant',
  'suspicious',
  'indecisive',
  'disbelieving',
  'pessimistic',
  'disillusioned',
  'disenchanted',
  'questioning',
  'unclear',
  'speculative',
  'distrustful',
  'reconsidering',
  'doubtful',
  'chary',
  'undetermined',
  'reserved',
  'unresolved',
  'uncertain',
  'ambivalent',
  'anxious',
  'undecided',
  'perplexed',
  'suspenseful',
  'equivocal',
  'mistrustful',
  'interrogative',
  'distracted',
  'wary',
  'waffling',
  'iffy',
  'nervous',
  'fearful',
  'unconvinced',
  'reluctant',
  'circumspect',
  'tentative',
  'wobbling',
  'skeptical',
  'cautious',
  'questionable',
  'hesitant',
  'unbelieving',
  'inquisitive',
  'unsettled',
  'leery'
}

doubt_adv = {
  'allegedly',
  'ambivalently',
  'apprehensively',
  'arguably',
  'barely',
  'basically',
  'cautiously',
  'circumspectly',
  'cynically',
  'decidedly',
  'disbelievingly',
  'distractedly',
  'distrustfully',
  'doubtfully',
  'dubiously',
  'equivocally',
  'fairly',
  'falteringly',
  'fearfully',
  'guardedly',
  'hesitantly',
  'indecisively',
  'inquisitively',
  'interrogatively',
  'jadedly',
  'mistrustfully',
  'nervously',
  'noncommittally',
  'occasionally',
  'partially',
  'partly',
  'perplexedly',
  'pessimistically',
  'possibly',
  'practically',
  'preferably',
  'presumably',
  'questionably',
  'questioningly',
  'quizzically',
  'relatively',
  'reluctantly',
  'reservedly',
  'roughly',
  'scantily',
  'seemingly',
  'skeptically',
  'slenderly',
  'slightly',
  'speculatively',
  'strictly',
  'suspiciously',
  'tentatively',
  'theoretically',
  'uncertainly',
  'unclearly',
  'virtually',
  'warily',
  'waveringly',
}

doubt_verbs = {
  'appear',
  'appraise',
  'assess',
  'assume',
  'be unsure of',
  'believe',
  'challenge',
  'consider',
  'contemplate',
  'debate',
  'deliberate',
  'disbelieve',
  'distrust',
  'doubt',
  'estimate',
  'examine',
  'expect',
  'falter',
  'feel',
  'guess',
  'hesitate',
  'hope',
  'imagine',
  'imply',
  'indicate',
  'infer',
  'inquire',
  'investigate',
  'muse',
  'ponder',
  'postulate',
  'presume',
  'probe',
  'query',
  'question',
  'reckon',
  'reconsider',
  'reflect',
  'rethink',
  'review',
  'scrutinize',
  'seem',
  'speculate',
  'suggest',
  'suppose',
  'suspect',
  'think',
  'understand',
  'vacillate',
  'waver'
}

############

predictive_modals = {"will", "would", "shall"}
possibility_modals = {"can", "may", "might", "could"}
necessity_modals = {"ought", "should", "must"}
